version: "1"

services:
  frontend:
    image: node
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    ports:
      - 3000:3000
    command: bash -c "npm install && npm run dev"
  backend:
    image: golang
    volumes:
      - ./backend/src:/app/backend
    working_dir: /app/backend
    ports:
      - 3001:3001
    command: bash -c "go mod tidy && go run main.go"
